name: Docker Build Edge

on: 
  push:
    paths-ignore:
      - 'README.md'

jobs:
  publish-to-docker-io:
    name: Publish to Docker.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: teakowa/docker-template
        cache: teakowa/docker-template
        tags: edge